use crate::canvas::actions::CanvasAction;

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum CanvasKeyAction {
    MoveLeft,
    MoveRight,
    MoveUp,
    MoveDown,
    NextField,
    PrevField,
    MoveLineStart,
    MoveLineEnd,
    MoveFirstLine,
    MoveLastLine,
    MoveWordNext,
    MoveWordPrev,
    MoveWordEnd,
    MoveWordEndPrev,
    MoveBigWordNext,
    MoveBigWordPrev,
    MoveBigWordEnd,
    MoveBigWordEndPrev,
    DeleteCharBackward,
    DeleteCharForward,
    Undo,
    Redo,
    OpenLineBelow,
    OpenLineAbove,
    EnterEditModeLineStart,
    EnterEditModeLineEnd,
    DeleteLine,
    DeleteToLineEnd,
    ChangeLine,
    ChangeToLineEnd,
    JoinLineBelow,
    OpenSuggestions,
    ApplySuggestion,
    EnterDecider,
    SuggestionDown,
    SuggestionUp,
    EnterEditModeBefore,
    EnterEditModeAfter,
    Exit,
    ExitEditMode,
    EnterHighlightMode,
    EnterHighlightModeLinewise,
    ExitHighlightMode,
    Unknown(String),
}

impl CanvasKeyAction {
    pub fn from_name(name: &str) -> Self {
        match name {
            "move_left" => Self::MoveLeft,
            "move_right" => Self::MoveRight,
            "move_up" => Self::MoveUp,
            "move_down" => Self::MoveDown,
            "next_field" => Self::NextField,
            "prev_field" => Self::PrevField,
            "move_line_start" => Self::MoveLineStart,
            "move_line_end" => Self::MoveLineEnd,
            "move_first_line" => Self::MoveFirstLine,
            "move_last_line" => Self::MoveLastLine,
            "move_word_next" => Self::MoveWordNext,
            "move_word_prev" => Self::MoveWordPrev,
            "move_word_end" => Self::MoveWordEnd,
            "move_word_end_prev" => Self::MoveWordEndPrev,
            "move_big_word_next" => Self::MoveBigWordNext,
            "move_big_word_prev" => Self::MoveBigWordPrev,
            "move_big_word_end" => Self::MoveBigWordEnd,
            "move_big_word_end_prev" => Self::MoveBigWordEndPrev,
            "delete_char_backward" => Self::DeleteCharBackward,
            "delete_char_forward" => Self::DeleteCharForward,
            "undo" => Self::Undo,
            "redo" => Self::Redo,
            "open_line_below" => Self::OpenLineBelow,
            "open_line_above" => Self::OpenLineAbove,
            "enter_edit_mode_line_start" => Self::EnterEditModeLineStart,
            "enter_edit_mode_line_end" => Self::EnterEditModeLineEnd,
            "delete_line" => Self::DeleteLine,
            "delete_to_line_end" => Self::DeleteToLineEnd,
            "change_line" => Self::ChangeLine,
            "change_to_line_end" => Self::ChangeToLineEnd,
            "join_line_below" => Self::JoinLineBelow,
            "open_suggestions" => Self::OpenSuggestions,
            "apply_suggestion" => Self::ApplySuggestion,
            "enter_decider" => Self::EnterDecider,
            "suggestion_down" => Self::SuggestionDown,
            "suggestion_up" => Self::SuggestionUp,
            "enter_edit_mode_before" => Self::EnterEditModeBefore,
            "enter_edit_mode_after" => Self::EnterEditModeAfter,
            "exit" => Self::Exit,
            "exit_edit_mode" => Self::ExitEditMode,
            "enter_highlight_mode" => Self::EnterHighlightMode,
            "enter_highlight_mode_linewise" => Self::EnterHighlightModeLinewise,
            "exit_highlight_mode" => Self::ExitHighlightMode,
            other => Self::Unknown(other.to_string()),
        }
    }

    pub fn as_str(&self) -> &str {
        match self {
            Self::MoveLeft => "move_left",
            Self::MoveRight => "move_right",
            Self::MoveUp => "move_up",
            Self::MoveDown => "move_down",
            Self::NextField => "next_field",
            Self::PrevField => "prev_field",
            Self::MoveLineStart => "move_line_start",
            Self::MoveLineEnd => "move_line_end",
            Self::MoveFirstLine => "move_first_line",
            Self::MoveLastLine => "move_last_line",
            Self::MoveWordNext => "move_word_next",
            Self::MoveWordPrev => "move_word_prev",
            Self::MoveWordEnd => "move_word_end",
            Self::MoveWordEndPrev => "move_word_end_prev",
            Self::MoveBigWordNext => "move_big_word_next",
            Self::MoveBigWordPrev => "move_big_word_prev",
            Self::MoveBigWordEnd => "move_big_word_end",
            Self::MoveBigWordEndPrev => "move_big_word_end_prev",
            Self::DeleteCharBackward => "delete_char_backward",
            Self::DeleteCharForward => "delete_char_forward",
            Self::Undo => "undo",
            Self::Redo => "redo",
            Self::OpenLineBelow => "open_line_below",
            Self::OpenLineAbove => "open_line_above",
            Self::EnterEditModeLineStart => "enter_edit_mode_line_start",
            Self::EnterEditModeLineEnd => "enter_edit_mode_line_end",
            Self::DeleteLine => "delete_line",
            Self::DeleteToLineEnd => "delete_to_line_end",
            Self::ChangeLine => "change_line",
            Self::ChangeToLineEnd => "change_to_line_end",
            Self::JoinLineBelow => "join_line_below",
            Self::OpenSuggestions => "open_suggestions",
            Self::ApplySuggestion => "apply_suggestion",
            Self::EnterDecider => "enter_decider",
            Self::SuggestionDown => "suggestion_down",
            Self::SuggestionUp => "suggestion_up",
            Self::EnterEditModeBefore => "enter_edit_mode_before",
            Self::EnterEditModeAfter => "enter_edit_mode_after",
            Self::Exit => "exit",
            Self::ExitEditMode => "exit_edit_mode",
            Self::EnterHighlightMode => "enter_highlight_mode",
            Self::EnterHighlightModeLinewise => "enter_highlight_mode_linewise",
            Self::ExitHighlightMode => "exit_highlight_mode",
            Self::Unknown(other) => other.as_str(),
        }
    }

    pub fn to_canvas_action(&self) -> Option<CanvasAction> {
        Some(match self {
            Self::MoveLeft => CanvasAction::MoveLeft,
            Self::MoveRight => CanvasAction::MoveRight,
            Self::MoveUp => CanvasAction::MoveUp,
            Self::MoveDown => CanvasAction::MoveDown,
            Self::MoveWordNext => CanvasAction::MoveWordNext,
            Self::MoveWordPrev => CanvasAction::MoveWordPrev,
            Self::MoveWordEnd => CanvasAction::MoveWordEnd,
            Self::MoveWordEndPrev => CanvasAction::MoveWordEndPrev,
            Self::MoveBigWordNext => CanvasAction::MoveBigWordNext,
            Self::MoveBigWordPrev => CanvasAction::MoveBigWordPrev,
            Self::MoveBigWordEnd => CanvasAction::MoveBigWordEnd,
            Self::MoveBigWordEndPrev => CanvasAction::MoveBigWordEndPrev,
            Self::MoveLineStart => CanvasAction::MoveLineStart,
            Self::MoveLineEnd => CanvasAction::MoveLineEnd,
            Self::NextField => CanvasAction::NextField,
            Self::PrevField => CanvasAction::PrevField,
            Self::MoveFirstLine => CanvasAction::MoveFirstLine,
            Self::MoveLastLine => CanvasAction::MoveLastLine,
            Self::DeleteCharBackward => CanvasAction::DeleteBackward,
            Self::DeleteCharForward => CanvasAction::DeleteForward,
            Self::Undo => CanvasAction::Undo,
            Self::Redo => CanvasAction::Redo,
            Self::OpenSuggestions => CanvasAction::TriggerSuggestions,
            Self::SuggestionUp => CanvasAction::SuggestionUp,
            Self::SuggestionDown => CanvasAction::SuggestionDown,
            Self::ApplySuggestion => CanvasAction::SelectSuggestion,
            Self::EnterEditModeBefore => CanvasAction::EnterEditMode,
            Self::EnterEditModeAfter => CanvasAction::EnterEditModeAfter,
            Self::ExitEditMode => CanvasAction::ExitEditMode,
            Self::EnterHighlightMode => CanvasAction::EnterHighlightMode,
            Self::EnterHighlightModeLinewise => CanvasAction::EnterHighlightModeLinewise,
            Self::ExitHighlightMode => CanvasAction::ExitHighlightMode,
            Self::OpenLineBelow => CanvasAction::OpenLineBelow,
            Self::OpenLineAbove => CanvasAction::OpenLineAbove,
            Self::EnterEditModeLineStart
            | Self::EnterEditModeLineEnd
            | Self::DeleteLine
            | Self::DeleteToLineEnd
            | Self::ChangeLine
            | Self::ChangeToLineEnd
            | Self::JoinLineBelow => return None,
            Self::EnterDecider | Self::Exit | Self::Unknown(_) => return None,
        })
    }
}
