[nor]
mode = "nor"
move_left = ["Left", "Ctrl+b"]
move_right = ["Right", "Ctrl+f"]
move_up = ["Up", "Ctrl+p"]
move_down = ["Down", "Ctrl+n"]
move_line_start = ["Home", "Ctrl+a"]
move_line_end = ["End", "Ctrl+e"]
move_word_next = ["Alt+f"]
move_word_prev = ["Alt+b"]
next_field = ["Tab", "Enter"]
prev_field = ["Shift+Tab"]
enter_edit_mode_before = ["i"]
enter_highlight_mode = ["Ctrl+space"]
paste_after = ["Ctrl+y"]
undo = ["Ctrl+/"]
redo = ["Alt+/"]

[ins]
mode = "ins"
exit_edit_mode = ["esc"]
move_left = ["Left", "Ctrl+b"]
move_right = ["Right", "Ctrl+f"]
move_up = ["Up", "Ctrl+p"]
move_down = ["Down", "Ctrl+n"]
move_line_start = ["Home", "Ctrl+a"]
move_line_end = ["End", "Ctrl+e"]
move_word_next = ["Alt+f"]
move_word_prev = ["Alt+b"]
next_field = ["Tab"]
prev_field = ["Shift+Tab"]
delete_char_backward = ["Backspace"]
delete_char_forward = ["Delete", "Ctrl+d"]
paste_after = ["Ctrl+y"]
open_suggestions = ["Ctrl+space"]
suggestion_down = ["Alt+n"]
suggestion_up = ["Alt+p"]
apply_suggestion = ["Enter"]
exit_suggestions = ["Ctrl+g"]

[sel]
mode = "sel"
exit_highlight_mode = ["esc"]
move_left = ["Left", "Ctrl+b"]
move_right = ["Right", "Ctrl+f"]
move_up = ["Up", "Ctrl+p"]
move_down = ["Down", "Ctrl+n"]
move_line_start = ["Home", "Ctrl+a"]
move_line_end = ["End", "Ctrl+e"]
move_word_next = ["Alt+f"]
move_word_prev = ["Alt+b"]
next_field = ["Tab"]
prev_field = ["Shift+Tab"]
delete_selection = ["Ctrl+w"]
yank_selection = ["Alt+w"]
paste_after = ["Ctrl+y"]
undo = ["Ctrl+/"]
redo = ["Alt+/"]
