[read_only]
mode = "read_only"
move_left = ["Left", "Ctrl+b"]
move_right = ["Right", "Ctrl+f"]
move_up = ["Up", "Ctrl+p"]
move_down = ["Down", "Ctrl+n"]
move_line_start = ["Home", "Ctrl+a"]
move_line_end = ["End", "Ctrl+e"]
move_word_next = ["Alt+f"]
move_word_prev = ["Alt+b"]
next_field = ["Tab", "Enter"]
prev_field = ["Shift+Tab"]
enter_edit_mode_before = ["i"]
enter_highlight_mode = ["Ctrl+space"]
undo = ["Ctrl+/"]
redo = ["Alt+/"]

[edit]
mode = "edit"
exit_edit_mode = ["esc"]
move_left = ["Left", "Ctrl+b"]
move_right = ["Right", "Ctrl+f"]
move_up = ["Up", "Ctrl+p"]
move_down = ["Down", "Ctrl+n"]
move_line_start = ["Home", "Ctrl+a"]
move_line_end = ["End", "Ctrl+e"]
move_word_next = ["Alt+f"]
move_word_prev = ["Alt+b"]
next_field = ["Tab"]
prev_field = ["Shift+Tab"]
delete_char_backward = ["Backspace"]
delete_char_forward = ["Delete", "Ctrl+d"]
undo = ["Ctrl+/"]
redo = ["Alt+/"]

[highlight]
mode = "highlight"
exit_highlight_mode = ["esc"]
move_left = ["Left", "Ctrl+b"]
move_right = ["Right", "Ctrl+f"]
move_up = ["Up", "Ctrl+p"]
move_down = ["Down", "Ctrl+n"]
move_line_start = ["Home", "Ctrl+a"]
move_line_end = ["End", "Ctrl+e"]
move_word_next = ["Alt+f"]
move_word_prev = ["Alt+b"]
next_field = ["Tab"]
prev_field = ["Shift+Tab"]
