[nor]
mode = "nor"
move_left = ["h", "Left"]
move_right = ["l", "Right"]
move_up = ["k", "Up"]
move_down = ["j", "Down"]
move_word_next = ["w"]
move_word_prev = ["b"]
move_word_end = ["e"]
move_big_word_next = ["W"]
move_big_word_prev = ["B"]
move_big_word_end = ["E"]
move_line_start = ["gh", "Home"]
move_line_end = ["gl", "End"]
move_half_page_up = ["Ctrl+u"]
move_half_page_down = ["Ctrl+d"]
move_first_line = ["gg"]
move_last_line = ["ge"]
next_field = ["Tab", "Enter"]
prev_field = ["Shift+Tab"]
enter_edit_mode_before = ["i"]
enter_edit_mode_after = ["a"]
enter_edit_mode_line_start = ["I"]
enter_edit_mode_line_end = ["A"]
enter_highlight_mode = ["v"]
extend_line_below = ["x"]
extend_to_line_bounds = ["X"]
collapse_selection = [";"]
search_next = ["n"]
search_prev = ["N"]
delete_selection = ["d"]
delete_selection_noyank = ["Alt+d"]
change_selection = ["c"]
change_selection_noyank = ["Alt+c"]
yank_selection = ["y"]
paste_after = ["p"]
paste_before = ["P"]
open_line_below = ["o"]
open_line_above = ["O"]
undo = ["u"]
redo = ["U"]

[ins]
mode = "ins"
exit_edit_mode = ["esc"]
move_left = ["Left"]
move_right = ["Right"]
move_up = ["Up"]
move_down = ["Down"]
move_line_start = ["Home"]
move_line_end = ["End"]
move_word_next = ["Alt+f"]
move_word_prev = ["Alt+b"]
next_field = ["Tab"]
prev_field = ["Shift+Tab"]
delete_char_backward = ["Backspace", "Ctrl+h"]
delete_char_forward = ["Delete", "Ctrl+d"]
delete_to_line_end = ["Ctrl+k"]
open_suggestions = ["Ctrl+x"]
suggestion_down = ["Ctrl+n"]
suggestion_up = ["Ctrl+p"]
apply_suggestion = ["Enter"]

[sel]
mode = "sel"
exit_highlight_mode = ["esc"]
enter_highlight_mode = ["v"]
extend_line_below = ["x"]
extend_to_line_bounds = ["X"]
collapse_selection = [";"]
move_left = ["h", "Left"]
move_right = ["l", "Right"]
move_up = ["k", "Up"]
move_down = ["j", "Down"]
move_word_next = ["w"]
move_word_prev = ["b"]
move_word_end = ["e"]
move_big_word_next = ["W"]
move_big_word_prev = ["B"]
move_big_word_end = ["E"]
move_line_start = ["gh", "Home"]
move_line_end = ["gl", "End"]
move_half_page_up = ["Ctrl+u"]
move_half_page_down = ["Ctrl+d"]
move_first_line = ["gg"]
move_last_line = ["ge"]
next_field = ["Tab"]
prev_field = ["Shift+Tab"]
delete_selection = ["d"]
delete_selection_noyank = ["Alt+d"]
change_selection = ["c"]
change_selection_noyank = ["Alt+c"]
yank_selection = ["y"]
paste_after = ["p"]
paste_before = ["P"]
undo = ["u"]
redo = ["U"]
