[read_only]
mode = "read_only"
move_left = ["h", "Left"]
move_right = ["l", "Right"]
move_up = ["k", "Up"]
move_down = ["j", "Down"]
move_word_next = ["w"]
move_word_prev = ["b"]
move_word_end = ["e"]
move_line_start = ["Home"]
move_line_end = ["End"]
move_first_line = ["gg"]
move_last_line = ["G"]
next_field = ["Tab", "Enter"]
prev_field = ["Shift+Tab"]
enter_edit_mode_before = ["i"]
enter_edit_mode_after = ["a"]
enter_highlight_mode = ["v"]
delete_char_forward = ["x"]
open_line_below = ["o"]
open_line_above = ["O"]
undo = ["u"]
redo = ["U"]

[edit]
mode = "edit"
exit_edit_mode = ["esc"]
move_left = ["Left"]
move_right = ["Right"]
move_up = ["Up"]
move_down = ["Down"]
move_line_start = ["Home"]
move_line_end = ["End"]
next_field = ["Tab"]
prev_field = ["Shift+Tab"]
delete_char_backward = ["Backspace"]
delete_char_forward = ["Delete"]
open_suggestions = ["Ctrl+space"]
suggestion_down = ["Ctrl+n"]
suggestion_up = ["Ctrl+p"]
apply_suggestion = ["Enter"]

[highlight]
mode = "highlight"
exit_highlight_mode = ["esc"]
move_left = ["h", "Left"]
move_right = ["l", "Right"]
move_up = ["k", "Up"]
move_down = ["j", "Down"]
move_word_next = ["w"]
move_word_prev = ["b"]
move_word_end = ["e"]
move_line_start = ["Home"]
move_line_end = ["End"]
move_first_line = ["gg"]
move_last_line = ["G"]
next_field = ["Tab"]
prev_field = ["Shift+Tab"]
