[nor]
mode = "nor"
clear_search = ["esc"]
move_left = ["h", "Left"]
move_right = ["l", "Right"]
move_up = ["k", "Up"]
move_down = ["j", "Down"]
move_word_next = ["w"]
move_word_prev = ["b"]
move_word_end = ["e"]
move_big_word_next = ["W"]
move_big_word_prev = ["B"]
move_big_word_end = ["E"]
move_line_start = ["gh", "Home"]
move_line_end = ["gl", "End"]
move_half_page_up = ["Ctrl+u"]
move_half_page_down = ["Ctrl+d"]
move_page_up = ["Ctrl+b", "PageUp"]
move_page_down = ["Ctrl+f", "PageDown"]
move_first_line = ["gg"]
move_last_line = ["ge", "G"]
goto_first_nonwhitespace = ["gs"]
next_field = ["Tab", "Enter"]
prev_field = ["Shift+Tab"]
enter_edit_mode_before = ["i"]
enter_edit_mode_after = ["a"]
enter_edit_mode_line_start = ["I"]
enter_edit_mode_line_end = ["A"]
enter_highlight_mode = ["v"]
extend_line_below = ["x"]
extend_to_line_bounds = ["X"]
collapse_selection = [";"]
select_all = ["%"]
flip_selections = ["Alt+;"]
switch_case = ["~"]
switch_to_lowercase = ["`"]
switch_to_uppercase = ["Alt+`"]
trim_selections = ["_"]
search_selection = ["*"]
ensure_selection_forward = ["Alt+:"]
match_brackets = ["mm"]
surround_add = ["ms"]
surround_delete = ["md"]
surround_replace = ["mr"]
join_line_below = ["J"]
indent_selection = [">"]
unindent_selection = ["<"]
increment_number = ["Ctrl+a"]
decrement_number = ["Ctrl+x"]
find_next_char = ["f"]
find_prev_char = ["F"]
till_next_char = ["t"]
till_prev_char = ["T"]
replace_char = ["r"]
repeat_last_find = ["Alt+."]
search_next = ["n"]
search_prev = ["N"]
delete_selection = ["d"]
delete_selection_noyank = ["Alt+d"]
change_selection = ["c"]
change_selection_noyank = ["Alt+c"]
yank_selection = ["y"]
paste_after = ["p"]
paste_before = ["P"]
open_line_below = ["o"]
open_line_above = ["O"]
undo = ["u"]
redo = ["U"]

[ins]
mode = "ins"
exit_edit_mode = ["esc"]
move_left = ["Left"]
move_right = ["Right"]
move_up = ["Up"]
move_down = ["Down"]
move_line_start = ["Home"]
move_line_end = ["End"]
move_word_next = ["Alt+f"]
move_word_prev = ["Alt+b"]
next_field = ["Tab"]
prev_field = ["Shift+Tab"]
delete_char_backward = ["Backspace", "Ctrl+h"]
delete_char_forward = ["Delete", "Ctrl+d"]
delete_to_line_end = ["Ctrl+k"]
delete_word_backward = ["Ctrl+w"]
delete_to_line_start = ["Ctrl+u"]
delete_word_forward = ["Alt+d"]
open_suggestions = ["Ctrl+x"]
suggestion_down = ["Ctrl+n"]
suggestion_up = ["Ctrl+p"]
apply_suggestion = ["Enter"]

[sel]
mode = "sel"
exit_highlight_mode = ["esc"]
enter_highlight_mode = ["v"]
extend_line_below = ["x"]
extend_to_line_bounds = ["X"]
collapse_selection = [";"]
select_all = ["%"]
flip_selections = ["Alt+;"]
switch_case = ["~"]
switch_to_lowercase = ["`"]
switch_to_uppercase = ["Alt+`"]
trim_selections = ["_"]
search_selection = ["*"]
ensure_selection_forward = ["Alt+:"]
match_brackets = ["mm"]
surround_add = ["ms"]
surround_delete = ["md"]
surround_replace = ["mr"]
join_line_below = ["J"]
indent_selection = [">"]
unindent_selection = ["<"]
increment_number = ["Ctrl+a"]
decrement_number = ["Ctrl+x"]
find_next_char = ["f"]
find_prev_char = ["F"]
till_next_char = ["t"]
till_prev_char = ["T"]
replace_char = ["r"]
repeat_last_find = ["Alt+."]
move_left = ["h", "Left"]
move_right = ["l", "Right"]
move_up = ["k", "Up"]
move_down = ["j", "Down"]
move_word_next = ["w"]
move_word_prev = ["b"]
move_word_end = ["e"]
move_big_word_next = ["W"]
move_big_word_prev = ["B"]
move_big_word_end = ["E"]
move_line_start = ["gh", "Home"]
move_line_end = ["gl", "End"]
move_half_page_up = ["Ctrl+u"]
move_half_page_down = ["Ctrl+d"]
move_page_up = ["Ctrl+b", "PageUp"]
move_page_down = ["Ctrl+f", "PageDown"]
move_first_line = ["gg"]
move_last_line = ["ge", "G"]
goto_first_nonwhitespace = ["gs"]
next_field = ["Tab"]
prev_field = ["Shift+Tab"]
delete_selection = ["d"]
delete_selection_noyank = ["Alt+d"]
change_selection = ["c"]
change_selection_noyank = ["Alt+c"]
yank_selection = ["y"]
paste_after = ["p"]
paste_before = ["P"]
undo = ["u"]
redo = ["U"]
