[nor]
mode = "nor"
move_left = ["h", "Left"]
move_right = ["l", "Right"]
move_up = ["k", "Up"]
move_down = ["j", "Down"]
move_word_next = ["w"]
move_word_prev = ["b"]
move_word_end = ["e"]
move_word_end_prev = ["ge"]
move_big_word_next = ["W"]
move_big_word_prev = ["B"]
move_big_word_end = ["E"]
move_big_word_end_prev = ["gE"]
move_line_start = ["0", "Home"]
move_line_end = ["$", "End"]
move_half_page_up = ["Ctrl+u"]
move_half_page_down = ["Ctrl+d"]
move_first_line = ["gg"]
move_last_line = ["G"]
next_field = ["Tab", "Enter"]
prev_field = ["Shift+Tab"]
enter_edit_mode_before = ["i"]
enter_edit_mode_after = ["a"]
enter_edit_mode_line_start = ["I"]
enter_edit_mode_line_end = ["A"]
enter_highlight_mode = ["v"]
enter_highlight_mode_linewise = ["V"]
delete_char_forward = ["x"]
delete_char_backward = ["X"]
delete_line = ["dd"]
delete_to_line_end = ["D"]
change_line = ["cc"]
change_to_line_end = ["C"]
join_line_below = ["J"]
yank_line = ["yy"]
paste_after = ["p"]
paste_before = ["P"]
open_line_below = ["o"]
open_line_above = ["O"]
find_next_char = ["f"]
find_prev_char = ["F"]
till_next_char = ["t"]
till_prev_char = ["T"]
repeat_last_find = [";"]
repeat_last_find_reverse = [","]
replace_char = ["r"]
switch_case = ["~"]
undo = ["u"]
redo = ["Ctrl+r"]

[ins]
mode = "ins"
exit_edit_mode = ["esc"]
move_left = ["Left"]
move_right = ["Right"]
move_up = ["Up"]
move_down = ["Down"]
move_line_start = ["Home"]
move_line_end = ["End"]
move_word_next = ["Ctrl+Right"]
move_word_prev = ["Ctrl+Left"]
next_field = ["Tab"]
prev_field = ["Shift+Tab"]
delete_char_backward = ["Backspace"]
delete_char_forward = ["Delete"]
open_suggestions = ["Ctrl+space"]
suggestion_down = ["Ctrl+n"]
suggestion_up = ["Ctrl+p"]
apply_suggestion = ["Ctrl+y"]

[sel]
mode = "sel"
exit_highlight_mode = ["esc"]
enter_highlight_mode = ["v"]
enter_highlight_mode_linewise = ["V"]
move_left = ["h", "Left"]
move_right = ["l", "Right"]
move_up = ["k", "Up"]
move_down = ["j", "Down"]
move_word_next = ["w"]
move_word_prev = ["b"]
move_word_end = ["e"]
move_word_end_prev = ["ge"]
move_big_word_next = ["W"]
move_big_word_prev = ["B"]
move_big_word_end = ["E"]
move_big_word_end_prev = ["gE"]
move_line_start = ["0"]
move_line_end = ["$"]
move_half_page_up = ["Ctrl+u"]
move_half_page_down = ["Ctrl+d"]
move_first_line = ["gg"]
move_last_line = ["G"]
next_field = ["Tab"]
prev_field = ["Shift+Tab"]
yank_line = ["y"]
delete_selection = ["d", "x"]
change_selection = ["c", "s"]
switch_case = ["~"]
indent_selection = [">"]
unindent_selection = ["<"]
find_next_char = ["f"]
find_prev_char = ["F"]
till_next_char = ["t"]
till_prev_char = ["T"]
repeat_last_find = [";"]
repeat_last_find_reverse = [","]
